#!/usr/bin/env ruby

lib_dir = File.expand_path("../lib", __dir__)
$LOAD_PATH.unshift(lib_dir) unless $LOAD_PATH.include?(lib_dir)

require "furaffinity"

SemanticLogger.sync!
SemanticLogger.add_appender(io: $stdout, formatter: :color)

Furaffinity::Cli.start
